/*******************************************************************************
 * @file can_id_allocation_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "can_id_allocation_dbc.h"

/** Public variables. *********************************************************/

const can_message_t allocation_dbc[] = {
    {
        .name = "node_id_discover",
        .message_id = 1823,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "session_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "node_id_advertise",
        .message_id = 1824,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "RESERVED_ADVERTISE",
                    .start_bit = 56,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "node_id_assign",
        .message_id = 1887,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ASSIGN",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_00",
        .message_id = 1888,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
};
