/*******************************************************************************
 * @file can_id_allocation_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "can_id_allocation_dbc.h"

/** Public variables. *********************************************************/

const can_message_t allocation_dbc[] = {
    {
        .name = "node_id_discover",
        .message_id = 1823,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "session_id",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "node_id_advertise",
        .message_id = 1824,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "RESERVED_ADVERTISE",
                    .start_bit = 56,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "node_id_assign",
        .message_id = 1887,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ASSIGN",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_00",
        .message_id = 1888,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_01",
        .message_id = 1889,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_02",
        .message_id = 1890,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_03",
        .message_id = 1891,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_04",
        .message_id = 1892,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_05",
        .message_id = 1893,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_06",
        .message_id = 1894,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_07",
        .message_id = 1895,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_08",
        .message_id = 1896,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_09",
        .message_id = 1897,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_10",
        .message_id = 1898,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_11",
        .message_id = 1899,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_12",
        .message_id = 1900,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_13",
        .message_id = 1901,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_14",
        .message_id = 1902,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_15",
        .message_id = 1903,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_16",
        .message_id = 1904,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_17",
        .message_id = 1905,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_18",
        .message_id = 1906,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_19",
        .message_id = 1907,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_20",
        .message_id = 1908,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_21",
        .message_id = 1909,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_22",
        .message_id = 1910,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_23",
        .message_id = 1911,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_24",
        .message_id = 1912,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_25",
        .message_id = 1913,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_26",
        .message_id = 1914,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_27",
        .message_id = 1915,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_28",
        .message_id = 1916,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_29",
        .message_id = 1917,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_30",
        .message_id = 1918,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
    {
        .name = "node_id_ack_31",
        .message_id = 1919,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signal_count = 6,
        .signals =
            {
                {
                    .name = "uid_hash48_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "uid_hash48_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "session_id",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "node_id",
                    .start_bit = 56,
                    .bit_length = 5,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "RESERVED_ACKNOWLEDGE",
                    .start_bit = 61,
                    .bit_length = 3,
                    .byte_order = CAN_LITTLE_ENDIAN,
                    .is_signed = false,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 7.0f,
                },
            },
    },
};
